### ISSUE TITLE
put hand crafted jobs under version control

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/ros_buildfarm#220]
I just notices these hand crafted jobs on Jenkins:
- http://build.ros.org/job/upload_main/
- http://build.ros.org/job/upload_testing/

Their configuration must be stored somewhere in a repository. Preferably they can be generated and redeployed as any other job.

**Comment by dirk-thomas** [comment]
Currently those jobs are only available from the `All` view since they get removed form the `Manage` view when ever that is regenerated.

**Comment by tfoote** [comment]
Yeah, we will need a way to only conditionally add them and parameterize them so we don't get other buildfarm instances trying to upload to our servers. (They won't have permissions but they will error etc)

**Comment by dirk-thomas** [comment]
This would be good to do before we try to redeploy a new buildfarm based on Xenial.

**Comment by dirk-thomas** [comment]
@nuclearsandwich How do you plan to address this ticket for the newly deployed buildfarm?

**Comment by nuclearsandwich** [comment]
self-assign in tandem with @tfoote to track this for myself.

> @nuclearsandwich How do you plan to address this ticket for the newly deployed buildfarm?

There's no immediate "this is how we do it" since currently the only bits that differentiate the canonical buildfarm from any other instance are in hiera for system configuration level details and in the ros_buildfarm_config for jenkins configuration (like whether or not to email maintainers).

I would strongly prefer _not_ to add configuration / option logic directly to this repo. That is, I think adding a cli arg like `--create-upload-jobs` is a poor solution. It puts configuration info at runtime and it's spread around enough already. Similarly, doing something insidious like only creating these jobs if the host is build.ros.org (or some other source defined constant) would also be a poor solution.

The specifications for buildfarm config yaml are versioned but I don't know how closely that's adhered to. My first instinct would be to add some config info to that repository and use that here to create these upload jobs or not.


Separately, the shell scripts that these jobs invoke `upload_{repo}.sh` do not seem to be versioned in the puppet config so we should add them there.

**Comment by dirk-thomas** [comment]
> My first instinct would be to add some config info to that repository and use that here to create these upload jobs or not.

That approach sounds good to me.

> Separately, the shell scripts that these jobs invoke upload_{repo}.sh do not seem to be versioned in the puppet config so we should add them there.

:+1:

**Comment by nuclearsandwich** [comment]
> My first instinct would be to add some config info to that repository and use that here to create these upload jobs or not.

@dirk-thomas are the buildfarm config scripts specified by an REP or are they versioned for parser/human convenience only?

**Comment by dirk-thomas** [comment]
> are the buildfarm config scripts specified by an REP or are they versioned for parser/human convenience only?

There is no REP for the config file format. The version number is being used in order to detect format changes if we decide to rollout any (rather failing to parse / handle older / newer config files not written for a specific version of the buildfarm). Compatible changes are applied to the config files as well as the `ros_buildfarm` logic whenever possible. But if any of the changes would break compatibility we would level the version to ensure if anyone using mismatching code vs. config gets a reasonable error message.

**Comment by nuclearsandwich** [comment]
Might be worth adding these to ros_buildfarm_config rather than the deployment puppet.

**Comment by nuclearsandwich** [comment]
These jobs are now on the farm and generated with the new script in #474. That script is not currently run as part of generate_all_jobs.py. But should only be needed on the canonical ROS buildfarm. This can either be closed now with the current state or we could log an issue to incorporate the new script into generate_all_jobs.py and add a section to the ros_buildfarm_config to take advantage of it.

**Comment by dirk-thomas** [comment]
Since the job config is now under version control and it is documented how to deploy these jobs I will close this ticket.
