### ISSUE TITLE
reconfigure missed to create new job

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/ros_buildfarm#268]
The PR for a new package was merged (http://build.ros.org/job/kinetic_rosdistro-cache/4169/) which triggered both reconfigure jobs passing the package name as the parameter.

* The ARM specific one (http://build.ros.org/job/Krel_arm_reconfigure-jobs/49/) did **not** create the new jobs.
* The non-ARM specific one (http://build.ros.org/job/Krel_reconfigure-jobs/61/) created the source and binary jobs for the new package successfully.

**Comment by dirk-thomas** [comment]
Also non of the common_tutorials jobs (http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__common_tutorials__ubuntu_xenial_amd64__binary/) got triggered automatically.

**Comment by tfoote** [comment]
On the test farm we saw a similar issue: 

This job got a new version of media_export: http://54.183.26.131:8080/job/kinetic_rosdistro-cache/3395/console  
```
15:35:51 DEBUG:rosdistro:Load package.xml file from url "https://raw.github.com/ros-gbp/media_export-release/release/kinetic/media_export/0.2.0-0/package.xml"
15:35:52   - updated manifest of package 'media_export' to version '0.2.0'
15:35:52   - fetch "message_filters"
```

And this seems to have successfully triggered the reconfigure job: http://54.183.26.131:8080/job/Krel_reconfigure-jobs/36/console

However it skips the reconfigure due to the package.xml not being in the cache: 
`15:36:20 Skipping package 'media_export': no released package.xml in cache`

All the new releases for kinetic today appear not to have been generated on the test farm, but the main farm it's working.

**Comment by dirk-thomas** [comment]
On the current test farm (as it is setup) this simply can't work.

The test farm is configured to use the official rosdistro repo and therefore also the cache generated by the official buildfarm. And the rosdistro jobs on the test farm only upload the generated caches to a temporary location on the repo machine. But when the reconfigure jobs are being triggered they use the cache provided by the official farm which might not have been regenerated yet.

**Comment by dirk-thomas** [comment]
I will close this since the referenced information is not available anymore and I haven't seen this problem since then. It can be reopened if we experience it again.
