### ISSUE TITLE
Per-job configuration (like -Werror)

### ISSUE THREAD

**Issue by scpeters** [ros-infrastructure/ros_buildfarm#291]
Is there any mechanism for being able to use non-default settings during the devel jobs, such as adding `-Werror` to `CMAKE_CXX_FLAGS`?

One option (maybe terrible) is to modify each specific package to check for an environment variable (like `JENKINS_HOME`) and set CI-specific options accordingly. Are there any better ideas than that?

**Comment by dirk-thomas** [comment]
There is currently no mechanism to specify custom settings for devel jobs. For the mentioned example (`-Werror`) we already extract all compiler warnings: http://build.ros.org/view/Kdev/job/Kdev__pluginlib__ubuntu_xenial_amd64/1/

But currently the build is not being marked as unstable in order to not notify the maintainers with this (since sadly too many packages are not building without warnings). Maybe we should enable this for newer distros and force people to fix their warnings if they have any?

**Comment by scpeters** [comment]
When I set `-Werror` in other projects, I usually make a big push to fix all the warnings and then turn on `-Werror`. It takes some buy-in from the maintainers. If they don't care, then it will be frustrating.

The only problem with marking as `unstable` is that isn't visible to travis. You have to click the link to see if there are warnings.

I don't have an easy answer.

**Comment by scpeters** [comment]
sorry not travis, I meant visible to the github build status

**Comment by dirk-thomas** [comment]
A maintainer can set `-Werror` anytime in the CMake code but we shouldn't force it.

The question is if we should actively notify them about the compiler warnings.

**Comment by dirk-thomas** [comment]
See ros-infrastructure/ros_buildfarm#293 and ros-infrastructure/ros_buildfarm_config#42.

**Comment by dirk-thomas** [comment]
I will close this ticket since we don't plan to expose package / repo specific configurations and warnings are now being reported (if the maintainer has enabled them).
