### ISSUE TITLE
Why does build failed for vision_visp packages on arm

### ISSUE THREAD

**Issue by fspindle** [ros-infrastructure/ros_buildfarm#368]
I can't figure out why the following packages are not building on arm with Kinetic:
- [visp_auto_tracker](http://build.ros.org/view/Kbin_dj_dJ64/job/Kbin_dj_dJ64__visp_auto_tracker__debian_jessie_amd64__binary/)
- [visp_camera_calibration](http://build.ros.org/view/Kbin_dj_dJ64/job/Kbin_dj_dJ64__visp_camera_calibration__debian_jessie_amd64__binary/)
- [visp_hand2eye_calibration](http://build.ros.org/view/Kbin_dj_dJ64/job/Kbin_dj_dJ64__visp_hand2eye_calibration__debian_jessie_amd64__binary/),
- [visp_tracker](http://build.ros.org/view/Kbin_dj_dJ64/job/Kbin_dj_dJ64__visp_tracker__debian_jessie_amd64__binary/)

and these on arm with Jade:
- [visp_auto_tracker](http://build.ros.org/view/Kbin_dj_dJ64/job/Kbin_dj_dJ64__visp_auto_tracker__debian_jessie_amd64__binary/)
- [visp_camera_calibration](http://build.ros.org/view/Kbin_dj_dJ64/job/Kbin_dj_dJ64__visp_camera_calibration__debian_jessie_amd64__binary/)
- [visp_hand2eye_calibration](http://build.ros.org/view/Kbin_dj_dJ64/job/Kbin_dj_dJ64__visp_hand2eye_calibration__debian_jessie_amd64__binary/)
- [visp_tracker](http://build.ros.org/view/Kbin_dj_dJ64/job/Kbin_dj_dJ64__visp_tracker__debian_jessie_amd64__binary/)

and these on arm with Indigo:
- [visp_auto_tracker](http://build.ros.org/view/Ibin_arm_uThf/job/Ibin_arm_uThf__visp_auto_tracker__ubuntu_trusty_armhf__binary/)
- [visp_hand2eye_calibration](http://build.ros.org/view/Ibin_arm_uThf/job/Ibin_arm_uThf__visp_hand2eye_calibration__ubuntu_trusty_armhf__binary/)
- [visp_tracker](http://build.ros.org/view/Ibin_arm_uThf/job/Ibin_arm_uThf__visp_tracker__ubuntu_trusty_armhf__binary/)

**Comment by dirk-thomas** [comment]
Looking through the build logs I noticed three classes of problems:

* Some of the builds have the status "aborted". That happens when one or more upstream projects are currently not building. In the first block of jobs that is currently the case for `visp_auto_tracker` and `visp_tracker`. If you follow the upstream job hierarchy you will find that `tf2` is currently failing to build (http://build.ros.org/view/Kbin_dj_dJ64/job/Kbin_dj_dJ64__tf2__debian_jessie_amd64__binary/12/). The maintainer will hopefully address this soon.

* [ ] Some jobs fail with `KeyError: 'ros-indigo-image-proc'`. The reason is that the Debian package is not available in the apt repo (http://repositories.ros.org/status_page/ros_indigo_arm.html?q=image_proc) despite the upstream job being green (http://build.ros.org/view/Ibin_arm_uThf/job/Ibin_arm_uThf__image_proc__ubuntu_trusty_armhf__binary/). It looks like that several arm packages have been removed from the apt repo during a recent rebuild (between end of January and early February), but the downstream jobs haven't been building. I would assume that is related to the recent Jenkins failure and restart. @tfoote Can you please review the inconsistencies between missing packages (e.g. http://repositories.ros.org/status_page/ros_indigo_arm.html?q=camera_calibration vs. http://build.ros.org/view/Ibin_arm_uThf/job/Ibin_arm_uThf__camera_calibration__ubuntu_trusty_armhf__binary/9/) and make sure the necessary jobs get triggered to create the missing Debian packages as soon as possible.

* [ ] Some jobs fail with `KeyError: 'apt-src'`. I have seen them before when Docker "missed" a layer / had a hiccup. I will have to look into those failures.

**Comment by dirk-thomas** [comment]
The `apt-src` problem should be fixed by #369.

**Comment by dirk-thomas** [comment]
Nvm, the PR didn't resolve the problem.

**Comment by dirk-thomas** [comment]
Regarding the specific missing upstream packages: I manually triggered http://build.ros.org/view/Ibin_arm_uThf/job/Ibin_arm_uThf__image_proc__ubuntu_trusty_armhf__binary/ which made your packages pass. @tfoote will have to handle this generically and ensure all Debian packages are there.

**Comment by dirk-thomas** [comment]
I will close this since #369 is tracking the `apt-src` problem.
