### ISSUE TITLE
email not sent to all recipients

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-infrastructure/ros_buildfarm#447]
Noticed that some failing jobs don't notify the maintainers even if they're listed in the job configuration:
e.g. [this job config](http://build.ros.org/job/Lbin_uX64__ompl__ubuntu_xenial_amd64__binary/config.xml) lists 3 recipients (search for "<recipients>") but [when it fails](http://build.ros.org/view/Lbin_uxhf_uXhf/job/Lbin_uxhf_uXhf__ompl__ubuntu_xenial_armhf__binary/47/console) only 2 recipients get notified (last lines of the build output)

**Comment by dirk-thomas** [comment]
The first two emails are coming from the buildfarm configuration and are statically configured within the job. The additional email is extracted on-the-fly from the processed package manifest (search for "Package maintainer emails:" in the console output). This extraction currently happens in a post build action. In the case of the build being terminated by a timeout the post build actions are not being run and therefore the job only contains two notification emails at that time.

I am not sure if the extraction of the maintainer emails could happen in an earlier phase but the current behavior is expected.

**Comment by mikaelarguedas** [comment]
I see, thanks for the explanation. 

> I am not sure if the extraction of the maintainer emails could happen in an earlier phase but

It would be great if we have a way to perform this action before. I think that it's valuable that the maintainers get notified when their builds fail (whether it's because of a build failure or a timeout)

**Comment by dirk-thomas** [comment]
The first referenced job is for Xenial amd64 and maintainer notification is enabled for that: https://github.com/ros-infrastructure/ros_buildfarm_config/blob/8c60b5f914827a469c88cd273568f8c16a5194b9/lunar/release-build.yaml#L13

The second referenced job is for Xenial armhf and maintainer notification is disabled for that: https://github.com/ros-infrastructure/ros_buildfarm_config/blob/8c60b5f914827a469c88cd273568f8c16a5194b9/lunar/release-xenial-armhf-build.yaml#L13

So it is expected behavior that the additional "Package maintainer emails" are only extracted in the first job but not in the second. Therefore I will close this.

You might want to consider enabling maintainer notification for armhf.

**Comment by mikaelarguedas** [comment]
thanks @dirk-thomas  for pointing it out. Open a follow-up at https://github.com/ros-infrastructure/ros_buildfarm_config/issues/84
