### ISSUE TITLE
Process for removing stale distribution

### ISSUE THREAD

**Issue by paulbovbel** [ros-infrastructure/ros_buildfarm#464]
This might be a feature request, or just a documentation clarification. We would like to be able to sunset a ROS distro on our buildfarm instance to free up clutter/resources.

Is there any standard/managed process for removing an 'old' ROS distribution from a live buildfarm instance? Removing the entries from ros_buildfarm_config/index.yaml and rosdistro/.../distribution.yaml isn't sufficient, as the Jenkins jobs hang around.

FYI @ayrton04

**Comment by dirk-thomas** [comment]
Usually we do the following steps:

* Remove the ROS distribution from the config (which stops the regeneration of the jobs).
  * This could also be only removing a specific target (e.g. an EOL Ubuntu distro) from rosdistro (e.g. ros/rosdistro#14517).
* Disable all jobs related to the distro / target in Jenkins using a handwritten Groovy script.
  * After this we usually wait a few weeks to ensure no critical fixes need to be shipped (since something last minute broke).
* Delete all jobs related to the distro / target in Jenkins using a handwritten Groovy script. You can see an example for a recent removal of Ubuntu Wily in https://gist.github.com/dirk-thomas/1baa9048b916b5fb71402f5edeb94971.

With Jade being EOL and planned to be removed in the near future (https://discourse.ros.org/t/jade-eol-announcement/2240) I will try to put the steps we follow into a `.rst` file in the `docs` in this repo. Hopefully that will help others.

**Comment by paulbovbel** [comment]
That would be a great help, thanks

**Comment by dirk-thomas** [comment]
Actually there was already a page mentioning this but the link was broken which made it difficult to find. Please see #465 for an updated version of the docs. Let me know if anything is unclear.
