### ISSUE TITLE
Doc jobs with hg started failing on December 20th

### ISSUE THREAD

**Issue by kmhallen** [ros-infrastructure/ros_buildfarm#502]
http://build.ros.org/job/Kdoc__dbw_mkz_ros__ubuntu_xenial_amd64/
http://build.ros.org/job/Idoc__dbw_mkz_ros__ubuntu_trusty_amd64/
http://build.ros.org/job/Idoc__rbdl__ubuntu_trusty_amd64/

**Comment by nuclearsandwich** [comment]
Additional jobs that are affected:

http://build.ros.org/view/Kdoc/job/Kdoc__mobility_base_ros__ubuntu_xenial_amd64
http://build.ros.org/view/Ldoc/job/Ldoc__ompl__ubuntu_xenial_amd64/

The timing of this correlates with #490 which was deployed the afternoon of 2017-12-18. Of all the jobs I've found the last successful run was [this one](http://build.ros.org/view/Ldoc/job/Ldoc__ompl__ubuntu_xenial_amd64/46/) at 3:56AM that same day.

Running a doc script locally to see if it's reproducible off of the farm.

**Comment by nuclearsandwich** [comment]
I was unable to reproduce the issue with a locally generated doc script.

The generate_doc_script.py line I used is below and from an up-to-date master clone of ros_buildfarm
```
generate_doc_script.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml lunar default ompl ubuntu xenial amd64
```

```
abort: there is no Mercurial repository here (.hg not found)
# END SUBSECTION
Traceback (most recent call last):
  File "/tmp/ros_buildfarm/scripts/doc/create_doc_task_generator.py", line 680, in <module>
    sys.exit(main())
  File "/tmp/ros_buildfarm/scripts/doc/create_doc_task_generator.py", line 149, in main
    current_hashes[args.repository_name] = get_hash(repo_dir)
  File "/tmp/ros_buildfarm/scripts/doc/create_doc_task_generator.py", line 593, in get_hash
    [hg, 'id', '--id'], cwd=path)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/hg', 'id', '--id']' returned non-zero exit status 255
```


In the segment above, the line beginning "abort:" is output from `hg` directly.
The lines after are output from the python failure to execute `/usr/bin/hg id --id` successfully.

Unfortunately, neither output offers insight into which directory was missing mercurial data. Accessing the workspace via ssh and running the command succeeds.

```
$ hg id --id
f5917ca25e64
```

The python process throwing this exception has the commandline:
```
python3 -u /tmp/ros_buildfarm/scripts/doc/create_doc_task_generator.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml --rosdistro-name lunar default --workspace-root /tmp/catkin_workspace --rosdoc-lite-dir /tmp/rosdoc_lite --catkin-sphinx-dir /tmp/catkin-sphinx --rosdoc-index-dir /tmp/rosdoc_index ompl --os-name ubuntu --os-code-name xenial --arch amd64 --vcs-info "hg default https://bitbucket.org/ompl/ompl.git" --distribution-repository-urls http://repositories.ros.org/ubuntu/testing --distribution-repository-key-files /tmp/keys/0.key --output-dir /tmp/generated_documentation --dockerfile-dir /tmp/docker_doc
```

The `repo_dir` variable is created from the `--workspace-root` and `repository_name` arguments. So from the commandline above it would be expected to be `/tmp/catkin_workspace/src/ompl` ([source](
https://github.com/ros-infrastructure/ros_buildfarm/blob/c0edd0d00732bf1444dfe2030b21eada2d72aa03/scripts/doc/create_doc_task_generator.py#L147-L149))

**Comment by nuclearsandwich** [comment]
I tried reverting the change introduced in #490 via the web UI. ([Job config history](http://build.ros.org/view/Ldoc/job/Ldoc__ompl__ubuntu_xenial_amd64/jobConfigHistory/configOutput?type=xml&timestamp=2018-01-19_15-03-31)) and was able to run a successful build.

I am not sure if this is an issue with Jenkins configurations expecting different names for the same "Default" configuration or if there's just some hgcache fallout from #490 that needs some other sideband fix.

**Comment by kmhallen** [comment]
Any update on this? The jobs continue to fail.

**Comment by nuclearsandwich** [comment]
I have reproduced these failures on a test buildfarm and here's what I've determined. The doc jobs, for reasons I still don't quite get, aren't working when the mercurial cache is properly enabled. Prior to #490 jobs on the buildfarm were using a hidden fallback `(Default)` rather than the specified `Default` installation. (The confusion around the hidden default is [ticketed upstream](https://issues.jenkins-ci.org/browse/JENKINS-14679)).

The hidden default does not use caching or sharing and so the doc jobs were running fine (though potentially more frequently than necessary). The fix for #488 involved switching the Mercurial installation from the hidden default `(Default)` to our `Default` installation. Which got caching working and started causing issues with the doc jobs.

I'm trying to dig further into why the cache is causing such issues but If I'm not able to resolve this one thing we could do in the interim is create a separate Mercurial installation config which doesn't use caching and have the doc jobs use it while we do more digging.

**Comment by kmhallen** [comment]
Disabling caching for Mercurial sounds like an adequate short-term solution

**Comment by nuclearsandwich** [comment]
Further investigation revealed that it is actually the sharing extension which is causing the failure. The shared hgcache directory (default path $HOME/hgcache)

I think we need both the sharing and caching enabled for the SCM polling to work correctly with elastic Jenkins nodes.

I was able to get the job working by mounting the hgcache directory in-place in the doc_task_generation container (`-v $HOME/hgcache:$HOME/hgcache`). Which is probably the quickest resolution to this issue but it's a bit on the messy side. The sharedpath pointer in the local repository uses an absolute path to the hgcache directory so we can't change the hgcache location and expect it to be found relative to the user's home directory within the container unless we also change that config file. I haven't explored that option so I don't know if it poses other issues. Another option would be to do a double clone, use the cached and shared hg repository to make a secondary clone which is neither cached nor shared and can be passed to a docker container being bound to other paths.

**Comment by tfoote** [comment]
I think the mount option is a common pattern so not too messy.

**Comment by nuclearsandwich** [comment]
> I think the mount option is a common pattern so not too messy.

I'm mostly perturbed by the fact that we're mounting a /home/jenkins-agent/hgcache directory within the container when no such user exists. I think mounting the hgcache is the optimal solution. If anyone else took umbrage with the nonsensical path within the container we would iterate on the solution. But if everyone else is satisfied I can stow my discomfort. Especially since each job reported in this issue has completed successfully since #526 was deployed.
