### ISSUE TITLE
Jenkins 2.89.4 shows first run wizard when installed

### ISSUE THREAD

**Issue by inigomartinez** [ros-infrastructure/ros_buildfarm#519]
Recently a new version [2.89.4](http://pkg.jenkins.io/debian-stable/binary/jenkins_2.89.4_all.deb) has been available through jenkins' repositories.

Although there isn't any error in the puppet logs, the buildfarm deployment script seems to be broken. When entering jenkins for the first time, the first time configuration wizard is shown asking for the plugins to be installed and the creation of an user.

**Comment by gavanderhoorn** [comment]
Hm. I recently upgraded to `.4` and then everything keeps working.

This is on a fresh deploy @inigomartinez? Anything in the puppet logs?

**Comment by inigomartinez** [comment]
Yes, it's on a fresh deploy. I've not seen anything relevant in the logs (though they are quite large).

I went back to the previous `2.89.3` and everything works properly.

**Comment by gavanderhoorn** [comment]
Without redeploying?

Anything in `/var/log/jenkins/jenkins.log`? `generate_all_jobs.py` fails silently then?

**Comment by inigomartinez** [comment]
I still don't know. I had the issue regarding the first time wizard and some issues regarding the agents (which didn't even show up when JNLPv2 was enabled) when I noticed that there was a new version installed. I had figured out what was issue after going back to `2.89.3`.

I'll try to do some more testing.

**Comment by nuclearsandwich** [comment]
@inigomartinez I saw the wizard with a new 2.89.4 deployment as well. You can disable it from the start by adding `-Djenkins.install.runSetupWizard=false` to the java_args (might be worth a PR to make that default but I'm pretty sure the wizard goes away once you start configuring things with the API.

**Comment by nuclearsandwich** [comment]
Actually, after a cup of coffee, I've just realized this is open on the ros_buildfarm scripts repository rather than the [buildfarm_deployment](https://github.com/ros-infrastructure/ros-buildfarm) repository. In general issues with running your own buildfarm should be reported in that repository first. If you're not sure whether something is an issue or not you're also welcome to ask on https://answers.ros.org/ I follow the jenkins, buildfarm, and buildfarm_deployment labels pretty closely.

I expect some of your other firstrun issues are related to https://github.com/ros-infrastructure/buildfarm_deployment/issues/177

I'm going to close this here since there's likely no action to be taken related to this repository.
