### ISSUE TITLE
should the virtualenv setup instructions be updated?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/ros_buildfarm#657]
The instructions in the [Virtualenv](https://github.com/ros-infrastructure/ros_buildfarm/blob/f1eaeb85e5536e03c0764895d6ed782701906d1f/doc/environment.rst#virtualenv) section of the *Setup environment to deploy configuration* use `pyvenv-3.4` with the `--no-pip` option to work around a bug.

I've always just used `virtualenv` itself or `python3 -m venv` and it appears that works for me.

The following steps result in a working venv with `ros_buildfarm` installed:

```bash
$ virtualenv -p python3 $HOME/venv_ros_buildfarm
$ source $HOME/venv_ros_buildfarm/bin/activate
$ pip3 install empy
$ pip3 install jenkinsapi
$ pip3 install rosdistro
$ pip3 install ros_buildfarm
```

Would it make sense to update the *Virtualenv* section with similar steps to avoid the mention of the `3.4` specific version (has confused people in the past) and the `pyvenv-3.4` use?

**Comment by dirk-thomas** [comment]
As the current instructions mention:

> The following commands can be used on Ubuntu Trusty:

Yes, since Trusty has reached its end-of-life (or more precisely end of standard support) updating them to a newer state would be great.

> I've always just used `virtualenv` itself or `python3 -m venv`

Both commands should work the same. I don't know if there is a preference for either or.

Any pull request to update the docs would be highly appreciated.

**Comment by gavanderhoorn** [comment]
See #658.
