### ISSUE TITLE
Add links to html-based test reports

### ISSUE THREAD

**Issue by max-krichenbauer** [ros-infrastructure/ros_buildfarm#693]
In the past, there was some effort to allow users to add more test suits to their packages that produce more complex html-based "dashboard" result pages, most notably [HAROS](https://github.com/git-afsantos/haros). (References: https://github.com/ros-infrastructure/ros_buildfarm/pull/685 , https://github.com/ros-infrastructure/ros_buildfarm/issues/596 )

Now that [pull/681](https://github.com/ros-infrastructure/ros_buildfarm/pull/681) was merged, the Hudson plug-in `htmlpublisher` also became available.
This should make it fairly easy to show links to those test results on the build page as suggested by [@dirk-thomas ](https://github.com/droter/roswiki/pull/1#issuecomment-565780527).

To my understanding, it would only need adding a snippet to `ros_buildfarm/templates/devel/devel_job.xml.em` to add something like the following to the job:

```xml
<htmlpublisher.HtmlPublisher plugin="htmlpublisher@@1.18">
  <reportTargets>
    <htmlpublisher.HtmlPublisherTarget>
      <reportName>HTML test reports</reportName>
      <reportDir>ws/test_results/</reportDir>
      <reportFiles>**/*.html</reportFiles>
      <alwaysLinkToLastBuild>true</alwaysLinkToLastBuild>
      <reportTitles></reportTitles>
      <keepAll>true</keepAll>
      <allowMissing>true</allowMissing>
      <includes>**/*</includes>
      <escapeUnderscores>true</escapeUnderscores>
    </htmlpublisher.HtmlPublisherTarget>
  </reportTargets>
</htmlpublisher.HtmlPublisher>
```

I'm not too familiar with Jenkins, but this should add links to all html files in the `test_results` directory, correct?
Would this be conceived a useful addition?

**Comment by tfoote** [comment]
Exposing the html outputs makes sense, however I'd suggest that we try to be a little bit more discriminating about what we expose besides `**/*.html` what we expose we should specifically select so that people don't come to rely or expect something that's less stable or unique to a package that then we can't easily present outside the buildfarm context.

**Comment by max-krichenbauer** [comment]
Thank you for the feedback @tfoote !
Sorry, I'm not quite sure if I understand what you mean though.

As far as I understand, current behavior is that all `.xml` files in the `test_results` folder get a link on the build page:
https://github.com/ros-infrastructure/ros_buildfarm/blob/591cf5539df8f97a8b8af2dcf142bc09c68f5ef5/ros_buildfarm/templates/devel/devel_job.xml.em#L265

Is there a difference to `.html` files in `test_results`?
Are there known cases of unwanted `.html` files ending up in `test_results` that should not be exposed?
Is there some mechanism to control which `.xml` or `.html` files should be linked to (other than controlling what tests should be run / which tests results should be generated?

Sorry if my questions show a lack of understanding.

**Comment by tfoote** [comment]
Connecting this back to https://github.com/ros-infrastructure/ros_buildfarm/pull/685 I think that this is a better way to host the test results.

There's not known cases of unwanted html files in the test results directory at the moment because we don't do anything with them. The question is down the line if it's known that any html files that are dropped into the test_results directory will be posted online and hosted by Open Robotics on high bandwidth servers there might be an issue. I don't want to arbitrarily just promise that we'll do that for anyone and everyone. We should specifically turn it on for things that we deem are worth the resources to generate and host. 

We do have limited resources for the hosting. In particular we have retention policies that clean up older job results because otherwise we run out of disk space surprisingly quickly.  We don't have control of what tests run, and they could dump out arbitrary html content. Besides malicious activity, examples are that many code coverage tests generate html outputs with annotated source etc.

The XML test outputs are something that we've specifically turned on and have specific benefit. We also will know if something is problematic if there's extra xml outputs because we have tools that are parsing them and will warn or error if there's xml content that's not unit test results.

We also want to be consistent and not just turn things on and off. If we add this general thing and people then come to rely on it, and then we decide that we can't support it and turn if off people will be unhappy. Whereas if we say we're going to support HAROS generated outputs in this location it's much more clearly scoped and we can estimate the costs/overhead etc better up front. Another consideration is that we need to understand the scope and location of things. If HAROS starts outputting in the root of the directory. That will mean that noone else can generate an index.html there so if another test result wants to be published, it's now potentially conflicting and someone else can't add the coverage report. Or alternatively package by package the urls are different as different maintainers choose a different higherarchy of locations for their packages.

Technically the above will make it happen for any/all of these cases. But what I'm asking for is to specifically know is what you'd like to host, where, so that we can review that and make a commitment to it. And if we make sure to standardize the paths etc we can do other things like scrape or integrate the results into other resources like index.ros.org but we can only do that if we consciously choose specific patterns.

**Comment by max-krichenbauer** [comment]
Thank you for the explanation. I perfectly understand.

I must admit that I'm not a ROS developer, so I have no personal use case.
I'm merely asking on behalf of the [QA Working Group](https://discourse.ros.org/t/next-ros-quality-assurance-working-group-january-2020/12013) where the idea of providing HAROS as a QA tool to developers is a common topic.

Currently, there are prototype implementations of [haros_catkin](https://github.com/rosin-project/haros_catkin) and [ament_haros](https://github.com/esol-community/ament_lint/tree/ament_haros) available to allow using HAROS on the build farm, but details about when or where reports are generated seems to be still [under discussion](https://github.com/rosin-project/haros_catkin/issues/14).

I think everyone's waiting for someone to just decide the details.

**Comment by tfoote** [comment]
Please see https://github.com/ros-infrastructure/ros_buildfarm/pull/685#issuecomment-589823708 We need estimates about the data size and expected volumes to be able to evaluate the tradeoffs of this request.

**Comment by dirk-thomas** [comment]
Closing due to age / inactivity.
