### ISSUE TITLE
prerelease overlay script does not respect --exclude-pkg

### ISSUE THREAD

**Issue by wjwwood** [ros-infrastructure/ros_buildfarm#74]
I think the root of the issue is that this function takes excluded packages, but never uses it:

https://github.com/ros-infrastructure/ros_buildfarm/blob/master/ros_buildfarm/prerelease.py#L39-L41

@dirk-thomas do you know where that parameter, `excluded_package_names`, should be used? I've read over the code, but it's a bit unclear to me which of these places it might should be added in:

https://github.com/ros-infrastructure/ros_buildfarm/blob/master/ros_buildfarm/prerelease.py#L80
https://github.com/ros-infrastructure/ros_buildfarm/blob/master/ros_buildfarm/prerelease.py#L93
https://github.com/ros-infrastructure/ros_buildfarm/blob/master/ros_buildfarm/prerelease.py#L104

To reproduce the issue I'm facing you can run this command:

```
$ ./scripts/prerelease/generate_prerelease_overlay_script.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/master/index.yaml indigo ubuntu trusty amd64 --level 1 --underlay-packages serial
```

And you'll see that `ax2550`, for example, is in the overlay, but this command:

```
$ ./scripts/prerelease/generate_prerelease_overlay_script.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/master/index.yaml indigo ubuntu trusty amd64 --level 1 --underlay-packages serial --exclude-pkg ax2550
```

Produces a result which still has the `ax2550` package in it. The dependency tree here is simple, `ax2550` depends on `serial` and nothing depends on `ax2550`.

The `--underlay-packages` option is something I added in the `prerelease_website` branch on this repository. It just lets you see the output without having any packages cloned locally:

https://github.com/ros-infrastructure/ros_buildfarm/compare/prerelease_website

**Comment by dirk-thomas** [comment]
It is indeed currently not used at all which is wrong.

* https://github.com/ros-infrastructure/ros_buildfarm/blob/master/ros_buildfarm/prerelease.py#L80 must pass `excluded_package_names` to the `excludes` argument to ignore excluded packages when traversing the reverse dependency tree. It determines what packages on-top should be built.
* For the other two cases excluding specific packages makes less sense since that means excluding a necessary dependency from the built. This would likely result in a failed build.
