### ISSUE TITLE
devel jobs are not using custom rosdep repository

### ISSUE THREAD

**Issue by dejanpan** [ros-infrastructure/ros_buildfarm#87]
This is a report from Bosch and ticketed as suggested by Tully.

We have a custom rosdep yaml (containing the output from the Mike Purvis’ rosdep-generator). This is properly used by the buildfarm’s binary-deb jobs, however, it is not used by the devel-builds in favor of the public rosdep repo.

This is the output of the “Idev_deepfield_ubuntu_trusty_amd64” job. As you can see, it does not pull the rosdep .yaml files from our server (“bfrepo”), and then fails because it cannot resolve the actionlib package:

 
```
23:36:45 reading in sources list data from /etc/ros/rosdep/sources.list.d

23:36:45 Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml

23:36:45 Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml

23:36:45 Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml

23:36:45 Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml

23:36:45 Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml

23:36:45 Query rosdistro index http://bfrepo/rosdistro/index.yaml

23:36:45 Add distro "indigo"

23:36:45 updated cache in /home/buildfarm/.ros/rosdep/sources.cache

23:36:45 Crawling for packages in workspace '/tmp/catkin_workspace/src'

23:36:46 Found the following packages:

23:36:46   - df-package1

23:36:46   - …

23:36:46 Package maintainer emails: …

23:36:48 Always install the following generic dependencies:

23:36:48   - build-essential

23:36:48   - python3

23:36:48   - ros-indigo-catkin

23:36:48 Identified the following build dependencies (ignoring packages available from source):

23:36:48   - actionlib

23:36:48   - …                         

23:36:48 Traceback (most recent call last):

23:36:48   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 196, in resolve_names

23:36:48     rosdep_key, view, installer, os_name, os_code_name)

23:36:48   File "/usr/lib/python3/dist-packages/rosdep2/catkin_support.py", line 81, in resolve_for_os

23:36:48     d = view.lookup(rosdep_key)

23:36:48   File "/usr/lib/python3/dist-packages/rosdep2/lookup.py", line 187, in lookup

23:36:48     return self.rosdep_defs[rosdep_name]

23:36:48 KeyError: 'actionlib'

23:36:48

23:36:48 During handling of the above exception, another exception occurred:

23:36:48

23:36:48 Traceback (most recent call last):

23:36:48   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 212, in <module>

23:36:48     main()

23:36:48   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 98, in main

23:36:48     debian_pkg_names_building = resolve_names(build_depends, **context)

23:36:48   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 199, in resolve_names

23:36:48     "Could not resolve the rosdep key '%s'" % rosdep_key)

23:36:48 RuntimeError: Could not resolve the rosdep key 'actionlib'
```
 

Why do the devel builds not use our custom rosdep repository like the release-builds do? Is this missing somewhere in our configuration files?

**Comment by tfoote** [comment]
So digging a little deeper, the release builds work because they do not use rosdep. The released packages already have had their rosdeps resolved by bloom etc and we've always pushed our test rosdep keys upstream. This won't work for a private deployment.

For a short term workaround you can simply inject it into the templates on your buildfarm. Like https://github.com/tfoote/ros_buildfarm/commit/8f7b95dc9b402e2667746ff0f8b41a6b78fb9e9b 

To be slightly cleaner this change could obviously be parameterized into the generate_devel_* jobs instead of hard coding a change. 

I'd want to discuss this with @dirk-thomas but I believe the correct fix is to use the _config section of the targets in the [release-build-file](http://www.ros.org/reps/rep-0137.html#release-build-file) to include a set of rosdep sources and have those get parametrized into the environment in addition to the envisioned additional repositories. 

Note, the spec has an example of adding extra repositories but the code does not support that at the moment either.

**Comment by tfoote** [comment]
That's true this is the source build it should probably be in the source build file as well.

**Comment by ddimarco** [comment]
Thanks, adding the rosdeps into the templates worked for us. I agree that putting the rosdeps in the config repo would be a nicer solution.
